#!/usr/bin/env bash

if [[ -s "/home/thuha/.rvm/environments/ruby-2.0.0-p0" ]]
then
  source "/home/thuha/.rvm/environments/ruby-2.0.0-p0"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/thuha/.rvm/environments/ruby-2.0.0-p0'" >&2
  exit 1
fi
