#!/usr/bin/env bash

if [[ -s "/home/thuha/.rvm/environments/ruby-1.9.3-p392@global" ]]
then
  source "/home/thuha/.rvm/environments/ruby-1.9.3-p392@global"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/thuha/.rvm/environments/ruby-1.9.3-p392@global'" >&2
  exit 1
fi
